### ISSUE TITLE
网络问题，无法连接到服务，请检查你的代理或本地网络连接后重试。 Network request failed

### ISSUE THREAD

**Issue by asd519627326** [LegendLeo/deeplx-serverless#1]
刚部署完好好的，不到半小时出现错误：“网络问题，无法连接到服务，请检查你的代理或本地网络连接后重试。 Network request failed”

**Comment by HuTsing** [comment]
我这边暂时没有碰到相关问题，请你提供相关错误截图，云函数配置截图

**Comment by asd519627326** [comment]
> 我这边暂时没有碰到相关问题，请你提供相关错误截图，云函数配置截图

![1](https://github.com/LegendLeo/deeplx-serverless/assets/88755813/ec7ca236-c84c-42a1-937f-9ae32043b0b6)
![2](https://github.com/LegendLeo/deeplx-serverless/assets/88755813/fbc607fd-1e04-44c6-ad2c-779924f070ec)

**Comment by HuTsing** [comment]
> > 我这边暂时没有碰到相关问题，请你提供相关错误截图，云函数配置截图
> 
> ![1](https://private-user-images.githubusercontent.com/88755813/313550773-ec7ca236-c84c-42a1-937f-9ae32043b0b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDg2NzUsIm5iZiI6MTcxMDc0ODM3NSwicGF0aCI6Ii84ODc1NTgxMy8zMTM1NTA3NzMtZWM3Y2EyMzYtYzg0Yy00MmExLTkzN2YtOWFlMzIwNDNiMGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA3NTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyY2RlMDE4OWE4ZmQ3ZTNjMTAzY2NmZDUwYWEwYjQwOWZjNzhjNmRiNTk1YjI1NTM0OTk5ZjVmYzU2ODkyYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tutc9Bs9uuI7HPaQFKqANt_MwWJojAPNEUGBO1Ibgw4) ![2](https://private-user-images.githubusercontent.com/88755813/313550798-fbc607fd-1e04-44c6-ad2c-779924f070ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDg2NzUsIm5iZiI6MTcxMDc0ODM3NSwicGF0aCI6Ii84ODc1NTgxMy8zMTM1NTA3OTgtZmJjNjA3ZmQtMWUwNC00NGM2LWFkMmMtNzc5OTI0ZjA3MGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA3NTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNTkyNzI2MTI5ZjI2NDcyODc4MjljYmViNDhlOTE0NGE1ODM5Njk2OWNhMDlkZGJjMDEyMzhmYzk0YWM3MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.51QcIeHUSdwrXY9FduUdAa-Nvoe7b9_xcdPns1KLOGY)

我推测是你当前网络连接香港服务有问题，你换大陆地区的环境配置再试试吧

**Comment by asd519627326** [comment]
> > > 我这边暂时没有碰到相关问题，请你提供相关错误截图，云函数配置截图
> > 
> > 
> > ![1](https://private-user-images.githubusercontent.com/88755813/313550773-ec7ca236-c84c-42a1-937f-9ae32043b0b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDg2NzUsIm5iZiI6MTcxMDc0ODM3NSwicGF0aCI6Ii84ODc1NTgxMy8zMTM1NTA3NzMtZWM3Y2EyMzYtYzg0Yy00MmExLTkzN2YtOWFlMzIwNDNiMGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA3NTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyY2RlMDE4OWE4ZmQ3ZTNjMTAzY2NmZDUwYWEwYjQwOWZjNzhjNmRiNTk1YjI1NTM0OTk5ZjVmYzU2ODkyYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tutc9Bs9uuI7HPaQFKqANt_MwWJojAPNEUGBO1Ibgw4) ![2](https://private-user-images.githubusercontent.com/88755813/313550798-fbc607fd-1e04-44c6-ad2c-779924f070ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDg2NzUsIm5iZiI6MTcxMDc0ODM3NSwicGF0aCI6Ii84ODc1NTgxMy8zMTM1NTA3OTgtZmJjNjA3ZmQtMWUwNC00NGM2LWFkMmMtNzc5OTI0ZjA3MGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA3NTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNTkyNzI2MTI5ZjI2NDcyODc4MjljYmViNDhlOTE0NGE1ODM5Njk2OWNhMDlkZGJjMDEyMzhmYzk0YWM3MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.51QcIeHUSdwrXY9FduUdAa-Nvoe7b9_xcdPns1KLOGY)
> 
> 我推测是你当前网络连接香港服务有问题，你换大陆地区的环境配置再试试吧

这个试过了北京的，还是不行。难道是我使用的移动宽带网络问题吗？我用移动网络连接不了deepl网站，换回手机联通热点可以连接上，不过这个同样试过，依然是出现错误。

**Comment by HuTsing** [comment]
云函数的代码下方有在线测试，看看这里能不能通，能通就仔细检查你自己的网络环境并修复
<img width="1553" alt="image" src="https://github.com/LegendLeo/deeplx-serverless/assets/25115173/e54e8564-21e3-447e-b63b-b98f452753ef">

**Comment by asd519627326** [comment]
> 云函数的代码下方有在线测试，看看这里能不能通，能通就仔细检查你自己的网络环境并修复 <img alt="image" width="1553" src="https://private-user-images.githubusercontent.com/25115173/315208931-e54e8564-21e3-447e-b63b-b98f452753ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTA0MDcsIm5iZiI6MTcxMTAxMDEwNywicGF0aCI6Ii8yNTExNTE3My8zMTUyMDg5MzEtZTU0ZTg1NjQtMjFlMy00NDdlLWI2M2ItYjk4ZjQ1Mjc1M2VmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA4MzUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZDM4OWU1ODYzM2Q3NjkyMTczM2EzNmQ2ZGMxNzljZmJkZjRkNDJkYTQ4MGQ4MDQ0OTkwMDIyZTg2ZTdlNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.03zml0h0108pjJ3h3-57K9xCJec-GbvRzB8Pi_NU3RE">

能通，是我本地网络问题，感谢解答
